version: '3'
services:
  mysql_maestro:
  #mysql-bin.000001  157 replica
    image: mysql:8.0
    container_name: mysql_maestro
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3306:3306"
    
  mysql_esclavo:
    image: mysql:8.0
    container_name: mysql_esclavo
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql_maestro
      - mysql_esclavo
    environment:
      PMA_HOSTS: mysql_maestro,mysql_esclavo
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
